### ISSUE TITLE
Default listener sets up on [::1]:9091 but not 127.0.0.1:9091

### ISSUE THREAD

**Issue by benbenwilde** [couchbaselabs/couchbase-elasticsearch-connector#132]
This is with the default setting (setting omitted) in elasticsearch.yml for `network.host`.
Workaround is to explicitly define `network.host: 127.0.0.1`.

**Comment by dnault** [comment]
Thanks for sharing the workaround, Ben.

Since this issue has a workaround, and since the new version of the connector is right around the corner, I'll close this as "won't fix". Let me know if you disagree with the severity.
