### ISSUE TITLE
[Question] How to set couchbase and elasticsearch hosts?

### ISSUE THREAD

**Issue by RezaOwliaei** [couchbaselabs/couchbase-elasticsearch-connector#193]
Hey!

I'm running couchbase v5.5 on `couchbase:8091` and elasticsearch v6.4  on `elasticsearch:11210`. I tried to set couchbase host on `/cbes/config/default-connector.toml` as following:

```
#using connector v4.0.0-dp.1
[couchbase]
    #hosts = ['localhost']
    hosts = ['couchbase']
    bucket = 'default'
[elasticsearch]
   #hosts = ['localhost']
   hosts = ['elasticsearch']
   username = 'elastic'
```

After running `cbes`, I'm still receiving following error:
```
12:47:28.402 [cb-io-3-1] WARN  c.c.c.c.e.Endpoint - [localhost:11210][KeyValueEndpoint]: Could not connect to remote socket: Connection refused: localhost/127.0.0.1:11210
12:47:28.442 [cb-io-3-3] WARN  c.c.c.c.e.Endpoint - [localhost:8091][ConfigEndpoint]: Could not connect to remote socket: Connection refused: localhost/127.0.0.1:8091
12:47:28.467 [main] WARN  c.c.c.d.CouchbaseHelper - Couchbase connection failure, couldn't open bucket. Retrying in 2s
```

How can I set the couchbase and es correct addresses?

Thanks in advanced.

**Comment by dnault** [comment]
Hi Reza, thanks for trying out the Developer Preview!

When the connector starts up, it logs the location of the config file it's using, and the contents of that file. For example:

    Reading connector configuration from /Users/david.nault/path/to/example-connector.toml
    12:56:17.187 [main] INFO  com.couchbase.connector.elasticsearch.ElasticsearchConnector - Read configuration: ConnectorConfig{couchbase=CouchbaseConfig{hosts=[localhost], username=Administrator, bucket=travel-sample, secureConnection=false, dcp=DcpConfig{compression=ENABLED, persistencePollingInterval=100ms, flowControlBuffer=128mb}}, elasticsearch=ElasticsearchConfig{hosts=[http://localhost:9200], username=elastic, secureConnection=false, bulkRequest=BulkRequestConfig{maxActions=1000, maxBytes=10mb, concurrentRequests=2, timeout=1m}, docStructure=DocStructureConfig{metadataFieldName=meta, documentContentAtTopLevel=false, wrapCounters=false}, types=[TypeConfig{type=_doc, ignore=true, ignoreDeletes=false, matcher=prefix='_sync:'}, TypeConfig{index=airlines, type=_doc, ignore=false, ignoreDeletes=false, matcher=prefix='airline_'}, TypeConfig{index=airports, type=_doc, ignore=false, ignoreDeletes=false, matcher=regex='.*port_.*'}, TypeConfig{index=etc, type=_doc, ignore=false, ignoreDeletes=false, matcher=prefix=''}], rejectLog=RejectLogConfig{index=cbes-rejects, typeName=_doc}}, metrics=MetricsConfig{logInterval=1m, httpPort=31415}, group=GroupConfig{name=example-group, staticMembership=1/1}, trustStore=TrustStoreConfig{path=path/to/truststore}}

Please can you confirm that the connector is reading the config file you expect, and the `CouchbaseConfig` and `ElasticsearchConfig` match the contents of that config file?

**Comment by dnault** [comment]
Also, I believe `11210` is a non-standard port for Elasticsearch. I believe you should be able to specify it like this:

    [elasticsearch]
      hosts = ['elasticsearch:11210']

**Comment by RezaOwliaei** [comment]
Thank you for your response, David.

The connector is reading expected config file perfectly and adding port to the hostname fixed the connectiton addresses.
Connection to Elasticsearch is failed however and I can't figure out why:
```
Reading connector configuration from /usr/share/elasticsearch/cbes/config/default-connector.toml
06:42:13.383 [main] INFO  c.c.c.e.ElasticsearchConnector - Read configuration: ConnectorConfig{couchbase=CouchbaseConfig{hosts=[couchbase:8091], username=Administrator, bucket=default, secureConnection=false, dcp=DcpConfig{compression=ENABLED, persistencePollingInterval=100ms, flowControlBuffer=128mb}}, elasticsearch=ElasticsearchConfig{hosts=[http://elasticsearch:11210], username=elastic, secureConnection=false, bulkRequest=BulkRequestConfig{maxActions=1000, maxBytes=10mb, concurrentRequests=2, timeout=1m}, docStructure=DocStructureConfig{metadataFieldName=meta, documentContentAtTopLevel=false, wrapCounters=false}, types=[TypeConfig{type=_doc, ignore=true, ignoreDeletes=false, matcher=prefix='_sync:'}, TypeConfig{index=gamete, type=_doc, ignore=false, ignoreDeletes=false, matcher=prefix=''}], rejectLog=RejectLogConfig{index=cbes-rejects, typeName=_doc}}, metrics=MetricsConfig{logInterval=1m, httpPort=31415}, group=GroupConfig{name=default-group, staticMembership=1/1}, trustStore=TrustStoreConfig{path=path/to/truststore}}
06:42:13.811 [main] INFO  c.c.c.u.HttpServer - HTTP server listening at http://localhost:31415
06:42:13.811 [main] INFO  c.c.c.e.ElasticsearchConnector - Metrics available at http://localhost:31415/metrics?pretty
06:42:14.027 [main] WARN  c.c.c.e.ElasticsearchHelper - Elasticsearch connection failure, couldn't get version. Retrying in 2s
```
I verified that elasticsearch is accessible:
```
sh-4.2# curl elasticsearch:9200
{
  "name" : "jVJOUdd",
  "cluster_name" : "gamete-cluster",
  "cluster_uuid" : "qGAi9JT6SiSYuoz6O8m4Kg",
  "version" : {
    "number" : "6.4.0",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "595516e",
    "build_date" : "2018-08-17T23:18:47.308994Z",
    "build_snapshot" : false,
    "lucene_version" : "7.4.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```
