### ISSUE TITLE
Listening address

### ISSUE THREAD

**Issue by isador999** [couchbaselabs/couchbase-elasticsearch-connector#81]
Elasticsearch 1.4.4  (Debian7), with the following lines in my '/etc/elasticsearch/elasticsearch.yml'  :  

network.publish_host: 192.X.X.X
network.host: 192.X.X.X
couchbase.username="username"
couchbase.password="pwd"
couchbase.port="9091"

The couchbase plugin is listening on `127.0.0.1:9091`.  
It's a problem when Elasticsearch and Couchbase are not on the same server...   

Only if the both lines `network` are commented, it's working, because elasticsearch AND couchbase-plugin will listen on all adresses.

**Comment by clakech** [comment]
do you find a way to have ES and CB working together on 2 different hosts ? I am doing the same using docker... still some work to do because I face a bug using this ES plugin (cf: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/issues/99)

**Comment by dnault** [comment]
For recent versions of Elasticsearch, the `network.host` property accepts special values like`_local_` and `_site_` that control which network interface ES binds to.

https://www.elastic.co/guide/en/elasticsearch/reference/6.4/network.host.html

    # bind to any loopback addresses (example: 127.0.0.1)
    # as well as any site-local addresses (example: 192.168.0.1)
    network.host: [_local_, _site_]
